  node:
    build: ./
    command: npm start
    depends_on:
      mongodb:
        condition: service_healthy 
    volumes:
      - .:/node
    ports:
      - ["5001"]

  redis:
    image: redis:5.0-alpine3.10
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    ports: ["6379"]

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - DATABASE_NAME=upskillNodejs
      - CONNECTION_URL=mongodb://localhost:27017/