version: "2"
services:
  node_app:
    build: .
    command: npm start
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - ./home/node_app/
    ports:
      - 5001:5001
    links:
      - db
      - redis

  redis:
    image: redis:7.0.2-alpine
    volumes:
      - "./healthchecks:/healthchecks"
    ports: ["6379"]

  db:
    image: mongo:5.0
    ports:
      - 27018:27017
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
