version: "2"
services:
  node:
    build: .
    command: npm start
    depends_on: 
      - mongodb
    volumes:
      - .:/node
    ports:
      - 5001:5001

  redis:
    image: redis:5.0-alpine3.10
    volumes:
      - "./healthchecks:/healthchecks"
    ports: ["6379"]

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db