version: "2"
services:
  node_app:
    build: .
    command: npm start
    restart: always
    depends_on:
      - db
      - myredis
    volumes:
      - ./home/node_app/
      - nodemodules:/node_modules
    ports:
      - 5001:5001
    links:
      - db
      - myredis

  myredis:
    container_name: myredis
    image: redis:latest
    volumes:
      - "./healthchecks:/healthchecks"
    ports: ["6379"]

  db:
    container_name: db
    image: mongo:5.0
    ports:
      - 27018:27017
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
  nodemodules: {}
